import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import React from "react";
import ReduxProvider from "@/components/ReduxProvider";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
    return (
        <html lang="en">
            <ReduxProvider>
                <body className={inter.className}>{children}</body>
            </ReduxProvider>
        </html>
    );
}
